title: Nový L.I.S.T.
email: aboelsaad1@uniba.sk
description: Bakalarska praca
baseurl: "/~aboelsaad1"
url: "https://davinci.fmph.uniba.sk"
twitter_username: 
github_username:  faresur

# Build settings
theme: 
plugins:
  - jekyll-feed
  - jekyll-seo-tag
